import { createContext, useContext, useState, useEffect, ReactNode } from "react";

// Cache buster - v8 - 2026-03-11T17:30:00 - Fixed routing with element prop and cache bust
type Language = "en" | "ja";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.home": "Home",
    "header.about": "About",
    "header.benefits": "Benefits",
    "header.apply": "Apply Now",
    "header.login": "Login",
    "header.logout": "Logout",
    
    // Home Page
    "home.hero.badge": "Trusted by top companies",
    "home.hero.title": "Launch Your",
    "home.hero.titleGradient": "Dream Career",
    "home.hero.subtitle": "Unlock opportunities. Our expert advisors provide personalized career guidance to help professionals in their 20s and 30s reach new heights.",
    "home.hero.cta": "Start Free Consultation",
    "home.stats.placements": "Placements",
    "home.stats.success": "Success Rate",
    "home.stats.companies": "Companies",
    "home.stats.rating": "Rating",
    "home.benefits.salary": "Salary $100K+",
    "home.benefits.weekends": "Weekends Off",
    "home.benefits.bonus": "Bi-Annual Bonus",
    "home.benefits.monthly": "Monthly Salary $6K+",
    "home.features.avgSalary": "Avg. Salary",
    "home.features.increase": "+40% increase from previous role",
    "home.features.experts": "Expert Advisors",
    "home.features.ready": "Ready to guide your success",
    "home.whyChoose": "Why Choose Us",
    "home.whyChoose.title": "Everything You Need to Succeed",
    "home.whyChoose.subtitle": "Comprehensive support from application to offer acceptance",
    "home.feature1.title": "Salary Increase Support",
    "home.feature1.subtitle": "Proven track record with young professionals",
    "home.feature2.title": "Document Support",
    "home.feature2.subtitle": "Complete interview preparation",
    "home.feature3.title": "Dedicated Advisor",
    "home.feature3.subtitle": "Comprehensive support throughout",
    "home.benefits.title": "Premium Benefits Package",
    "home.about.label": "About Mediverse Careers",
    "home.about.title": "What is Mediverse Careers",
    "home.about.description": "Mediverse Careers provides career advancement opportunities for professionals in their 20s and 30s. From document preparation to interview preparation, we offer personalized support to unlock your potential and achieve high success rates. Whether you're considering a career change or exploring your options, feel free to reach out to us.",
    "home.services.title": "Our Services",
    "home.services.subtitle": "Comprehensive career support tailored to your needs",
    "home.service1.title": "Career Counseling",
    "home.service1.description": "One-on-one guidance from experienced career advisors to help you find the perfect role.",
    "home.service2.title": "Resume Building",
    "home.service2.description": "Expert assistance in crafting compelling resumes and cover letters that stand out.",
    "home.service3.title": "Interview Prep",
    "home.service3.description": "Mock interviews and personalized feedback to boost your confidence and performance.",
    "home.service4.title": "Salary Negotiation",
    "home.service4.description": "Strategic advice to help you secure competitive compensation packages.",
    "home.service5.title": "Skill Assessment",
    "home.service5.description": "Identify your strengths and areas for growth to maximize your career potential.",
    "home.service6.title": "Networking Support",
    "home.service6.description": "Connect with industry professionals and expand your professional network.",
    "home.cta.title": "Ready to Advance Your Career?",
    "home.cta.subtitle": "Join thousands of professionals who have successfully transformed their careers with our support.",
    "home.cta.button": "Start Your Free Consultation",
    
    // Apply Page
    "apply.back": "Back to Home",
    "apply.badge": "Free Career Consultation",
    "apply.title": "Start Your",
    "apply.titleGradient": "Career Journey",
    "apply.subtitle": "Fill out the form below and we'll match you with opportunities that align with your goals",
    "apply.section1": "Personal Information",
    "apply.firstName": "First Name",
    "apply.lastName": "Last Name",
    "apply.email": "Email Address",
    "apply.phone": "Phone Number",
    "apply.firstNamePlaceholder": "John",
    "apply.lastNamePlaceholder": "Doe",
    "apply.emailPlaceholder": "john.doe@example.com",
    "apply.phonePlaceholder": "+1 (555) 123-4567",
    "apply.section2": "Professional Background",
    "apply.currentRole": "Current Job Title",
    "apply.experience": "Years of Experience",
    "apply.goals": "Career Goals",
    "apply.currentRolePlaceholder": "Software Engineer",
    "apply.experiencePlaceholder": "3",
    "apply.goalsPlaceholder": "Tell us about your career aspirations, dream role, target salary, and what you're looking for in your next opportunity...",
    "apply.section3": "Upload Resume",
    "apply.resume": "Resume / CV (Optional)",
    "apply.uploadText": "Click to upload or drag and drop",
    "apply.uploadFormats": "PDF, DOC, DOCX (Max 5MB)",
    "apply.changeFile": "Click to change file",
    "apply.referral": "How did you hear about us?",
    "apply.referralPlaceholder": "Google search, friend referral, LinkedIn, etc.",
    "apply.submit": "Submit Application",
    "apply.terms": "By submitting this form, you agree to our Terms of Service and Privacy Policy. We will contact you within 24 hours to schedule your free consultation.",
    
    // Login Page
    "login.back": "Back to Home",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.emailPlaceholder": "you@example.com",
    "login.passwordPlaceholder": "Enter your password",
    "login.forgot": "Forgot password?",
    "login.signin": "Sign In",
    "login.signingIn": "Signing in...",
    "login.noAccess": "Don't have access?",
    "login.contact": "Contact us to request login credentials for the management dashboard.",
    "login.error": "Invalid email or password",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back, Nami",
    "dashboard.welcomeBack": "Welcome back, ",
    "dashboard.subtitle": "Here's what's happening with your candidates today",
    "dashboard.totalCandidates": "Total Candidates",
    "dashboard.interviewsToday": "Interviews Today",
    "dashboard.pendingActions": "Pending Actions",
    "dashboard.today": "Today",
    "dashboard.followUps": "Follow-ups",
    "dashboard.notification1": "3 candidates waiting for first call",
    "dashboard.notification2": "2 interview reminders",
    "dashboard.notification3": "1 resume requested",
    "dashboard.followup1": "Candidate hasn't responded in 3 days",
    "dashboard.followup2": "Interview tomorrow reminder",
    "dashboard.followup3": "Candidate withdrew",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.viewCandidates": "View All Candidates",
    "dashboard.scheduleInterview": "Schedule Interview",
    "dashboard.reviewResumes": "Review Resumes",
    "dashboard.applicants": "Applicants",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.subtitle": "You have 6 new notifications",
    "notifications.viewAll": "View All Notifications",
    
    // Calendar
    "calendar.title": "Today's Interviews",
    "calendar.today": "Today",
    "calendar.selectDate": "Select Date",
    "calendar.scheduledInterviews": "Scheduled Interviews",
    "calendar.interviewsScheduled": "interviews scheduled for today",
    "calendar.upcoming": "Upcoming",
    "calendar.viewDetails": "View Details",
    "calendar.reschedule": "Reschedule",
    "calendar.sendInvite": "Send Invite Now",
    "calendar.shareCalendar": "Share Calendar",
    "calendar.close": "Close",
    "calendar.scheduleNew": "Schedule New Interview",
    
    // Applicants Page
    "applicants.title": "Applicants",
    "applicants.subtitle": "Manage and review all candidate applications",
    "applicants.searchPlaceholder": "Search by name or job...",
    "applicants.statusAll": "All Statuses",
    "applicants.statusInterviewScheduled": "Interview Scheduled",
    "applicants.statusScreening": "Screening",
    "applicants.statusFirstCall": "First Call",
    "applicants.statusOffered": "Offered",
    "applicants.statusRejected": "Rejected",
    "applicants.statusInterview Scheduled": "Interview Scheduled",
    "applicants.statusFirst Call": "First Call",
    "applicants.priorityHigh": "High",
    "applicants.priorityMedium": "Medium",
    "applicants.priorityLow": "Low",
    "applicants.export": "Export",
    "applicants.import": "Import File",
    "applicants.switchToExport": "Switch to Export",
    "applicants.switchToImport": "Switch to Import",
    "applicants.results": "Showing {{count}} results",
    "applicants.name": "Name",
    "applicants.age": "Age",
    "applicants.source": "Source",
    "applicants.desiredJob": "Desired Job",
    "applicants.status": "Status",
    "applicants.priority": "Priority",
    "applicants.nextAction": "Next Action",
    "applicants.actions": "Actions",
    "applicants.viewProfile": "View",
    "applicants.delete": "Delete",
    "applicants.deleteConfirm": "Are you sure?",
    "applicants.deleteMessage": "This action cannot be undone. This will permanently delete the candidate.",
    "applicants.deleteCancel": "Cancel",
    "applicants.deleteConfirmButton": "Delete",
    "applicants.newApplicants": "New Applicants",
    "applicants.newApplicantsSubtitle": "Candidates in screening status",
    "applicants.activeApplicants": "Active Applicants",
    "applicants.activeApplicantsSubtitle": "Candidates in active recruitment process",
    "applicants.addNew": "Add Candidate",
    "applicants.sendResumeBuilder": "Send Resume Builder",
    "applicants.sendResumeBuilderDesc": "Send a link to active applicants to fill in their resume",
    
    // Send Resume Builder Page
    "sendResume.title": "Resume Builder",
    "sendResume.subtitle": "履歴書作成ツールのフォームを完成させるための招待を送信",
    "sendResume.backToProfile": "プロフィールに戻る",
    "sendResume.applicantDetails": "候補者詳細",
    "sendResume.name": "名前",
    "sendResume.email": "メールアドレス",
    "sendResume.message": "メッセージ",
    "sendResume.subject": "件名",
    "sendResume.messageBody": "メッセージ",
    "sendResume.linkPreview": "履歴書作成ツールのリンク（含まれます）",
    "sendResume.cancel": "キャンセル",
    "sendResume.send": "送信",
    "sendResume.sending": "送信中...",
    "sendResume.copyLink": "リンクをコピー",
    "sendResume.copied": "コピーしました！",
    "sendResume.defaultSubject": "履歴書作成ツール - 次のステップ",
    "sendResume.defaultMessage": (name: string) => `拝啓 ${name} 様,\n\nこれまでのご協力に心より感謝申し上げます。プロセスを継続するため、以下のリンクから履歴書情報を入力してください。\n\nhttps://mediverse-career.com/applicants/new/20260792/TY/applicant/resumebuilder/\n\nよろしくお願いいたします。\n\n敬具,\n大山 様`,
    "sendResume.sentSuccess": "メールが正常に送信されました！",
    "sendResume.sentSuccessMessage": "履歴書作成ツールの招待が送信されました",
    "sendResume.confirmTitle": "メール送信完了",
    "sendResume.confirmButton": "OK",
    "sendResume.close": "OK",
    
    // History
    "sendResume.history": "履歴",
    "sendResume.historyTitle": "活動履歴",
    "sendResume.noHistory": "まだ活動がありません",
    "sendResume.emailSent": "メール送信先",
    "sendResume.formStatus": "フォームの状況",
    "sendResume.notStarted": "未開始",
    "sendResume.inProgress": "進行中",
    "sendResume.completed": "完了",
    "sendResume.closeHistory": "閉じる",
    "sendResume.completionRate": "完了率",
    "sendResume.lastSent": "最終送信日",
    "sendResume.sentCount": "送信回数",
    "sendResume.resendEmail": "メールを再送信",
    "sendResume.resending": "再送信中...",
    "sendResume.resentSuccess": "メールが正常に再送信されました",
    
    // Applications Page
    "applications.title": "Applications",
    "applications.subtitle": "Manage submitted job applications",
    "applications.searchPlaceholder": "Search by name, job, or email...",
    "applications.results": "Showing {{count}} applications",
    "applications.name": "Name",
    "applications.age": "Age",
    "applications.desiredJob": "Desired Job",
    "applications.email": "Email",
    "applications.phone": "Phone",
    "applications.submittedDate": "Submitted",
    "applications.actions": "Actions",
    "applications.viewProfile": "View",
    "applications.delete": "Delete",
    "applications.pendingApplications": "Pending Applications",
    "applications.pendingSubtitle": "Applications waiting for review",
    "applications.cancelledApplications": "Cancelled Applications",
    "applications.cancelledSubtitle": "Applications that have been cancelled",
    "applications.expand": "Expand",
    "applications.collapse": "Collapse",
    "applications.deleteConfirm": "Are you sure?",
    "applications.deleteMessage": "This will permanently delete this cancelled application.",
    "applications.deleteCancel": "Cancel",
    "applications.deleteConfirmButton": "Delete",
    
    // Add Candidate Page
    "addCandidate.title": "Add New Candidate",
    "addCandidate.subtitle": "Choose a method to add a candidate to your database",
    "addCandidate.backToApplicants": "Back to Applicants",
    "addCandidate.manualEntry": "Manual Entry",
    "addCandidate.manualEntryDesc": "Fill out the form fields manually",
    "addCandidate.pasteText": "Paste Text",
    "addCandidate.pasteTextDesc": "AI auto-parses pasted candidate information",
    "addCandidate.uploadScreenshot": "Upload Screenshot",
    "addCandidate.uploadScreenshotDesc": "AI extracts data from screenshot",
    "addCandidate.nameKanji": "Name (Kanji)",
    "addCandidate.nameKana": "Name (Kana)",
    "addCandidate.email": "Email",
    "addCandidate.phone": "Phone",
    "addCandidate.age": "Age",
    "addCandidate.gender": "Gender",
    "addCandidate.male": "Male",
    "addCandidate.female": "Female",
    "addCandidate.other": "Other",
    "addCandidate.source": "Source",
    "addCandidate.desiredJob": "Desired Job",
    "addCandidate.addButton": "Add Candidate",
    "addCandidate.pasteTitle": "Paste Candidate Information",
    "addCandidate.pasteDescription": "Paste any candidate information (resume text, email, profile data, etc.) and our AI will automatically extract and structure the relevant data.",
    "addCandidate.pastePlaceholder": "Paste candidate information here, for example:\\n\\nName: 田中 優希 (Tanaka Yuki)\\nAge: 27\\nEmail: tanaka.yuki@example.com\\nPhone: +81 90-1234-5678\\nDesired Job: Sales Manager\\nSource: Career Park\\n\\nOr paste any format - our AI will parse it!",
    "addCandidate.aiPowered": "AI-Powered:",
    "addCandidate.aiParseDescription": "Our intelligent parser will extract names, contact details, job preferences, and more from any text format.",
    "addCandidate.parseButton": "Parse & Add Candidate",
    "addCandidate.processing": "Processing...",
    "addCandidate.uploadTitle": "Upload Screenshot",
    "addCandidate.uploadDescription": "Upload a screenshot of candidate information (from a website, spreadsheet, PDF, or any source) and our AI will extract the relevant data.",
    "addCandidate.uploadText": "Click to upload or drag and drop",
    "addCandidate.uploadFormats": "PNG, JPG, or PDF (MAX. 10MB)",
    "addCandidate.removeFile": "Remove",
    "addCandidate.aiVision": "AI Vision:",
    "addCandidate.aiVisionDescription": "Our advanced OCR and AI vision technology will read the screenshot and automatically extract structured candidate data.",
    "addCandidate.extractButton": "Extract & Add Candidate",
    "addCandidate.extracting": "Extracting Data...",
    "addCandidate.required": "*",
    
    // Applicant Profile Page
    "profile.title": "Applicant Profile",
    "profile.backToApplicants": "Back to Applicants",
    "profile.saveChanges": "Save Changes",
    "profile.section1": "Section 1 — Basic Information",
    "profile.section2": "Section 2 — Career Background",
    "profile.section3": "Section 3 — Recruiter Notes",
    "profile.timeline": "Candidate Timeline",
    "profile.nameKanji": "Name (Kanji)",
    "profile.nameKana": "Name (Kana)",
    "profile.gender": "Gender",
    "profile.male": "Male",
    "profile.female": "Female",
    "profile.other": "Other",
    "profile.dateOfBirth": "Date of Birth",
    "profile.age": "Age",
    "profile.phone": "Phone",
    "profile.email": "Email",
    "profile.leadDate": "Lead Date (流入日)",
    "profile.university": "University",
    "profile.currentJob": "Current Job",
    "profile.currentCompany": "Current Company",
    "profile.yearsInCurrentJob": "Years in Current Job",
    "profile.reasonForLeaving": "Reason for Leaving",
    "profile.previousJob": "Previous Job",
    "profile.previousCompany": "Previous Company",
    "profile.yearsInPreviousJob": "Years in Previous Job",
    "profile.totalCompanies": "Total Number of Companies Worked",
    "profile.totalWorkExperience": "Total Work Experience (years)",
    "profile.note1": "Current job-hunting status:",
    "profile.note2": "Current job details / length of employment:",
    "profile.note3": "Reason for wanting to change jobs from your current position:",
    "profile.note4": "Previous job details / length of employment:",
    "profile.note5": "Reason for leaving your previous job:",
    "profile.note6": "Total number of companies you have worked for so far:",
    "profile.note7": "Preferred start date:",
    "profile.note8": "Desired job type / position:",
    "profile.note9": "Preferred work location:",
    "profile.note10": "Current annual salary / desired annual salary:",
    "profile.summarizeWithAI": "Summarize with AI",
    "profile.proceedWithApplication": "Proceed with Application",
    "profile.cancelApplication": "Cancel Application",
    "profile.addNewEvent": "Add New Event",
    "profile.eventDate": "Date",
    "profile.eventDescription": "Event description",
    "profile.addEvent": "Add",
    "profile.aiSummaryTitle": "AI Summary",
    "profile.saveSummary": "Save Summary",
    "profile.cancelConfirm": "Are you sure you want to cancel this application?",
    "profile.applicationCancelled": "Application cancelled",
    "profile.proceedingWithApplication": "Proceeding with application...",
    "profile.changesSaved": "Changes saved successfully!",
    "profile.summarySaved": "Summary saved successfully!",
    "profile.match": "Match",
    
    // Job Match Page
    "match.title": "Job Matching",
    "match.subtitle": "Match candidate with job opportunities",
    "match.backToProfile": "Back to Profile",
    "match.inputMethod": "Input Method",
    "match.pasteText": "Paste Job Description",
    "match.uploadFile": "Upload Screenshot/PDF",
    "match.jobDescription": "Job Description",
    "match.pasteJobDesc": "Paste job description text here...",
    "match.uploadText": "Click to upload or drag and drop",
    "match.uploadFormats": "PNG, JPG, or PDF (MAX. 10MB)",
    "match.removeFile": "Remove",
    "match.analyzeCompatibility": "Analyze Compatibility",
    "match.analyzing": "Analyzing...",
    "match.results": "Compatibility Results",
    "match.matchingScore": "Matching Score",
    "match.reason": "Reason",
    "match.proposalReason": "Proposal Reason",
    "match.jobImage": "Job Image",
    "match.postJoinImage": "Post-Join Image",
    "match.futureProspects": "Future Prospects",
    "match.addJob": "Add Another Job",
    "match.aiAnalyzing": "AI is analyzing candidate profile and job requirements...",
    "match.delete": "Delete",
    "match.addToProfile": "Add to Applicant Profile",
    "match.selectJobsFirst": "Please select at least one job to add to the profile",
    "match.jobsAddedToProfile": "Selected jobs added to applicant profile successfully!",
    
    // Resume Builder
    "resumeBuilder.title": "Resume Builder",
    "resumeBuilder.subtitle": "Create your professional resume step-by-step",
    "resumeBuilder.step1": "Resume File Information",
    "resumeBuilder.step2": "ID Photo",
    "resumeBuilder.step3": "Profile",
    "resumeBuilder.step4": "Current Address",
    "resumeBuilder.step5": "Experience",
    "resumeBuilder.step6": "Motivation / Self-Promotion",
    "resumeBuilder.step7": "Commuting & Family",
    "resumeBuilder.step8": "Personal Requests",
    "resumeBuilder.step9": "Review & Submit",
    "resumeBuilder.next": "Next",
    "resumeBuilder.previous": "Previous",
    "resumeBuilder.submit": "Submit Resume",
    "resumeBuilder.fileName": "File Name",
    "resumeBuilder.fileNameNote": "Since the hiring company will view this, please use an appropriate file name.",
    "resumeBuilder.creationDate": "Creation Date",
    "resumeBuilder.idPhoto": "ID Photo",
    "resumeBuilder.uploadPhoto": "Click to upload or drag and drop",
    "resumeBuilder.photoRequirements": "Please provide a photo with a 4:3 aspect ratio taken within the last 3 months.\\nSunglasses and hats are not allowed (NG). Provide a photo where you are clearly identifiable.\\nThe photo should be a solo shot from the chest up, with the full head visible within the frame.\\nA blue (light blue) or white background is recommended.",
    "resumeBuilder.fullName": "Full Name",
    "resumeBuilder.familyName": "Family Name",
    "resumeBuilder.givenName": "Given Name",
    "resumeBuilder.fullNameKana": "Full Name (Kana/Phonetic)",
    "resumeBuilder.familyNameKana": "Family Name (Kana)",
    "resumeBuilder.givenNameKana": "Given Name (Kana)",
    "resumeBuilder.dateOfBirth": "Date of Birth",
    "resumeBuilder.dateOfBirthNote": "Year, month, day",
    "resumeBuilder.gender": "Gender",
    "resumeBuilder.male": "Male",
    "resumeBuilder.female": "Female",
    "resumeBuilder.other": "Other",
    "resumeBuilder.noPhoto": "No photo uploaded",
    "resumeBuilder.fullNameKanji": "Full Name (Kanji)",
    "resumeBuilder.postalCode": "Postal Code (Required)",
    "resumeBuilder.currentAddress": "Current Address (Required)",
    "resumeBuilder.currentAddressKana": "Current Address (Kana/Phonetic) (Required)",
    "resumeBuilder.email": "Email Address",
    "resumeBuilder.phoneNumber": "Phone Number",
    "resumeBuilder.photoRequirementsTitle": "Photo Requirements:",
    "resumeBuilder.photoFormat": "PNG, JPG, JPEG (4:3 aspect ratio recommended)",
    "resumeBuilder.reviewFileName": "File Name:",
    "resumeBuilder.reviewCreationDate": "Creation Date:",
    "resumeBuilder.reviewFamilyNameKanji": "Family Name (Kanji):",
    "resumeBuilder.reviewGivenNameKanji": "Given Name (Kanji):",
    "resumeBuilder.reviewFamilyNameKana": "Family Name (Kana):",
    "resumeBuilder.reviewGivenNameKana": "Given Name (Kana):",
    "resumeBuilder.reviewDateOfBirth": "Date of Birth:",
    "resumeBuilder.reviewGender": "Gender:",
    "resumeBuilder.reviewPostalCode": "Postal Code:",
    "resumeBuilder.reviewCurrentAddressKanji": "Current Address (Kanji):",
    "resumeBuilder.reviewCurrentAddressKana": "Current Address (Kana):",
    "resumeBuilder.reviewEmail": "Email:",
    "resumeBuilder.reviewPhoneNumber": "Phone Number:",
    "resumeBuilder.reviewSkillDefault": "Skill",
    "resumeBuilder.reviewLanguageDefault": "Language",
    "resumeBuilder.workExperience": "Work Experience",
    "resumeBuilder.addExperience": "Add Experience",
    "resumeBuilder.companyName": "Company Name",
    "resumeBuilder.position": "Position",
    "resumeBuilder.startDate": "Start Date",
    "resumeBuilder.endDate": "End Date",
    "resumeBuilder.currentlyWorking": "Currently Working",
    "resumeBuilder.responsibilities": "Main Responsibilities and Achievements",
    "resumeBuilder.education": "Education",
    "resumeBuilder.addEducation": "Add Education",
    "resumeBuilder.schoolName": "School Name / University",
    "resumeBuilder.degree": "Degree / Qualification",
    "resumeBuilder.fieldOfStudy": "Field of Study",
    "resumeBuilder.graduationDate": "Graduation Date",
    "resumeBuilder.skills": "Professional Skills",
    "resumeBuilder.addSkill": "Add Skill",
    "resumeBuilder.skillName": "Skill Name",
    "resumeBuilder.proficiencyLevel": "Proficiency Level",
    "resumeBuilder.beginner": "Beginner",
    "resumeBuilder.intermediate": "Intermediate",
    "resumeBuilder.advanced": "Advanced",
    "resumeBuilder.expert": "Expert",
    "resumeBuilder.languages": "Languages",
    "resumeBuilder.addLanguage": "Add Language",
    "resumeBuilder.languageName": "Language",
    "resumeBuilder.languageLevel": "Level",
    "resumeBuilder.native": "Native",
    "resumeBuilder.fluent": "Fluent",
    "resumeBuilder.conversational": "Conversational",
    "resumeBuilder.basic": "Basic",
    "resumeBuilder.reviewInfo": "Review Information",
    "resumeBuilder.reviewDesc": "Please review all information before submitting",
    "resumeBuilder.submitting": "Submitting...",
    "resumeBuilder.successMessage": "Resume submitted successfully!",
    "resumeBuilder.delete": "Delete",
    "resumeBuilder.workHistory": "職歴",
    "resumeBuilder.addWork": "項目を追加",
    "resumeBuilder.licenses": "免許・資格",
    "resumeBuilder.addLicense": "項目を追加",
    "resumeBuilder.licenseName": "免許・資格名",
    "resumeBuilder.issuingOrganization": "発行機関",
    "resumeBuilder.dateObtained": "取得日",
    "resumeBuilder.highSchool": "高等学校",
    "resumeBuilder.associateDegree": "短期大学士",
    "resumeBuilder.bachelorsDegree": "学士",
    "resumeBuilder.mastersDegree": "修士",
    "resumeBuilder.doctorate": "博士",
    "resumeBuilder.yes": "はい",
    "resumeBuilder.no": "いいえ",
    "resumeBuilder.reviewSchoolDefault": "学校",
    "resumeBuilder.reviewCompanyDefault": "会社",
    "resumeBuilder.reviewLicenseDefault": "免許",
    "resumeBuilder.educationRequired": "※ 応募には少なくとも1つのエントリーが必要です",
    "resumeBuilder.motivationTitle": "志望動機・自己PR",
    "resumeBuilder.motivationPlaceholder": "例）自己PRについては別紙に記載",
    "resumeBuilder.commutingTitle": "通勤時間・家族構成",
    "resumeBuilder.commutingMethod": "通勤方法",
    "resumeBuilder.commutingTime": "通勤時間",
    "resumeBuilder.commutingTimePlaceholder": "例：1時間",
    "resumeBuilder.dependentsCount": "扶養家族数（配偶者を除く）",
    "resumeBuilder.hasSpouse": "配偶者",
    "resumeBuilder.spouseSupport": "配偶者の扶養義務",
    "resumeBuilder.personalRequestsTitle": "本人希望欄",
    "resumeBuilder.personalRequestsPlaceholder": "例）貴社の規定に従います。",
    "resumeBuilder.characterCount": "文字数：{{count}}/400",
    
    // Job Positions
    "job.productManager": "Product Manager",
    "job.dataAnalyst": "Data Analyst",
    "job.softwareEngineer": "Software Engineer",
    "job.marketingManager": "Marketing Manager",
    "job.salesRepresentative": "Sales Representative",
    "job.hrSpecialist": "HR Specialist",
    "job.uxDesigner": "UX Designer",
    
    // Statuses
    "status.newApplicant": "New Applicant",
    "status.inReview": "In Review",
    "status.interviewScheduled": "Interview Scheduled",
    "status.screening": "Screening",
    "status.firstCall": "First Call",
    "status.offered": "Offered",
    "status.rejected": "Rejected",
    
    // Sources
    "source.linkedin": "LinkedIn",
    "source.indeed": "Indeed",
    "source.referral": "Referral",
    "source.website": "Website",
    "source.careerPark": "CareerPark",
    "source.mynavi": "MyNavi",
    
    // Next Actions
    "action.scheduleInterview": "Schedule Interview",
    "action.reviewResume": "Review Resume",
    "action.firstCall": "First Call",
    "action.sendOffer": "Send Offer",
    "action.followUp": "Follow Up",
    
    // Notifications
    "notification.passwordChanged": "Your password has been successfully changed.",
    "notification.meetingBooked": "Thank you for booking a meeting with us.",
    "notification.fundLaunch": "Great news! We are launching our 5th fund: DLE Senior Living.",
    "notification.author1": "Kevin Durkoin",
    "notification.author2": "Markus Gavrilov",
    "notification.markAsRead": "Mark as read",
    "notification.viewAll": "View all notifications",
    
    // Additional Resume Builder Fields
    "resumeBuilder.applicationReason": "Reason for Application",
    "resumeBuilder.applicationReasonPlaceholder": "Why are you interested in this position?",
    "resumeBuilder.selfPromotion": "Self-Promotion / Personal Strengths",
    "resumeBuilder.selfPromotionPlaceholder": "Describe your key strengths and what makes you a great candidate...",
    "resumeBuilder.careerGoals": "Career Goals",
    "resumeBuilder.careerGoalsPlaceholder": "What are your career aspirations?",
    "resumeBuilder.transportationMethod": "Transportation Method",
    "resumeBuilder.transportationMethodPlaceholder": "e.g., Train, Car, Bicycle",
    "resumeBuilder.dependents": "Number of Dependents (excluding spouse)",
    "resumeBuilder.dependentsPlaceholder": "e.g., 0, 1, 2",
    "resumeBuilder.spouseEmploymentStatus": "Spouse Employment Status",
    "resumeBuilder.selectOption": "Select an option",
    "resumeBuilder.employed": "Employed",
    "resumeBuilder.unemployed": "Unemployed",
    "resumeBuilder.notApplicable": "N/A (Not Applicable)",
    "resumeBuilder.salaryExpectations": "Salary Expectations",
    "resumeBuilder.salaryExpectationsPlaceholder": "e.g., $80,000 - $100,000",
    "resumeBuilder.desiredWorkLocation": "Desired Work Location",
    "resumeBuilder.desiredWorkLocationPlaceholder": "e.g., Tokyo, Remote",
    "resumeBuilder.startDate": "Desired Start Date",
    "resumeBuilder.startDatePlaceholder": "e.g., April 2026",
    "resumeBuilder.otherRequests": "Other Requests",
    "resumeBuilder.otherRequestsPlaceholder": "Any additional requests or considerations...",
    "resumeBuilder.reviewMessage": "Please review all your information before submitting.",
    "resumeBuilder.confirmMessage": "By submitting, you confirm that all information provided is accurate and complete.",
  },
  ja: {
    // Header
    "header.home": "ホーム",
    "header.about": "会社概要",
    "header.benefits": "福利厚生",
    "header.apply": "応募する",
    "header.login": "ログイン",
    "header.logout": "ログアウト",
    
    // Home Page
    "home.hero.badge": "トップ企業に信頼されています",
    "home.hero.title": "あなたの",
    "home.hero.titleGradient": "理想のキャリアを実現",
    "home.hero.subtitle": "機会を開拓します。専門家アドバイザーが20代と30代の専門職に対してパーソナライズされたキャリアガイダンスを提供し、新たな高みへと導きます。",
    "home.hero.cta": "無料相談を開始",
    "home.stats.placements": "採用実績",
    "home.stats.success": "成功率",
    "home.stats.companies": "企業",
    "home.stats.rating": "評価",
    "home.benefits.salary": "年収1000万円以上",
    "home.benefits.weekends": "週末休み",
    "home.benefits.bonus": "年2回のボーナス",
    "home.benefits.monthly": "月収60万円以上",
    "home.features.avgSalary": "平均給与",
    "home.features.increase": "前職から+40%増加",
    "home.features.experts": "専門アドバイザー",
    "home.features.ready": "あなたの成功をサポート",
    "home.whyChoose": "選ばれる理由",
    "home.whyChoose.title": "成功に必要なすべて",
    "home.whyChoose.subtitle": "応募から内定承諾まで包括的なサポート",
    "home.feature1.title": "給与アップサポート",
    "home.feature1.subtitle": "若手専門職での実績",
    "home.feature2.title": "書類サポート",
    "home.feature2.subtitle": "完全な面接準備",
    "home.feature3.title": "専任アドバイザー",
    "home.feature3.subtitle": "全面的なサポート",
    "home.benefits.title": "プレミアム福利厚生パッケージ",
    "home.about.label": "Mediverse Careersについて",
    "home.about.title": "Mediverse Careersとは",
    "home.about.description": "Mediverse Careersは20代と30代の専門職にキャリアアップの機会を提供しま。書類作成から面接準備まで、パーソナライズされたサポートであなたの可能性を引き出し、高い成功率を実現します。キャリアチェンジを検討中でも、選択肢を探しているだけでも、お気軽にご連絡ください。",
    "home.services.title": "私たちのサービス",
    "home.services.subtitle": "あなたのニーズに合わせた包括的なキャリアサポート",
    "home.service1.title": "キャリアカウンセリング",
    "home.service1.description": "経験豊富なキャリアアドバイザーによるマンツーマンガイダンスで、最適な職種を見つけるお手伝いをします。",
    "home.service2.title": "履歴書作成",
    "home.service2.description": "目を引く履歴書とカバーレターの作成を専門家がサポートします。",
    "home.service3.title": "面接準備",
    "home.service3.description": "模擬面接とパーソナライズされたフィードバックで、自信とパフォーマンスを向上させます。",
    "home.service4.title": "給与交渉",
    "home.service4.description": "競争力のある報酬パッケージを確保するための戦略的アドバイスを提供します。",
    "home.service5.title": "スキル評価",
    "home.service5.description": "強みと成長分野を特定し、キャリアの可能性を最大化します。",
    "home.service6.title": "ネットワーキングサポート",
    "home.service6.description": "業界の専門家とつながり、プロフェッショナルネットワークを拡大します。",
    "home.cta.title": "キャリアアップの準備はできましたか？",
    "home.cta.subtitle": "私たちのサポートでキャリアを変革した何千人もの専門家に参加してください。",
    "home.cta.button": "無料相談を開始する",
    
    // Apply Page
    "apply.back": "ホームに戻る",
    "apply.badge": "無料キャリア相談",
    "apply.title": "あなたの",
    "apply.titleGradient": "キャリアを始めよう",
    "apply.subtitle": "以下のフォームに記入してください。あなたの目標に合った機会をご紹介します",
    "apply.section1": "個人情報",
    "apply.firstName": "名前",
    "apply.lastName": "姓",
    "apply.email": "メールアドレス",
    "apply.phone": "電話番号",
    "apply.firstNamePlaceholder": "太郎",
    "apply.lastNamePlaceholder": "山田",
    "apply.emailPlaceholder": "taro.yamada@example.com",
    "apply.phonePlaceholder": "+81 90-1234-5678",
    "apply.section2": "職務経歴",
    "apply.currentRole": "現在の職種",
    "apply.experience": "経験年数",
    "apply.goals": "キャリア目標",
    "apply.currentRolePlaceholder": "ソフトウェアエンジニア",
    "apply.experiencePlaceholder": "3",
    "apply.goalsPlaceholder": "キャリアの希望、理想の役割、目標給与、次の機会に求めることについて教えてください...",
    "apply.section3": "履歴書のアップロード",
    "apply.resume": "履歴書 / CV（任意）",
    "apply.uploadText": "クリックしてアップロードまたはドラッグ＆ドロップ",
    "apply.uploadFormats": "PDF、DOC、DOCX（最大5MB）",
    "apply.changeFile": "クリックしてファイルを変更",
    "apply.referral": "当社をどこで知りましたか？",
    "apply.referralPlaceholder": "Google検索、友人の紹介、LinkedInなど",
    "apply.submit": "応募を送信",
    "apply.terms": "このフォームを送信することで、利用規約とプライバシーポリシーに同意したものとみなされます。24時間以内に無料相談の予約についてご連絡いたします。",
    
    // Login Page
    "login.back": "���ームに戻る",
    "login.email": "メールアドレス",
    "login.password": "パスワード",
    "login.emailPlaceholder": "you@example.com",
    "login.passwordPlaceholder": "パスワードを入力",
    "login.forgot": "パスワードをお忘れですか？",
    "login.signin": "ログイン",
    "login.signingIn": "ログイン中...",
    "login.noAccess": "アクセス権がありませんか？",
    "login.contact": "管理ダッシュボードのログイン認証情報をリクエストするには、お問い合わせください。",
    "login.error": "メールアドレスまたはパスワードが無効です",
    
    // Dashboard
    "dashboard.title": "ダッシュボード",
    "dashboard.welcome": "おかえりなさい、ナミ",
    "dashboard.welcomeBack": "おかえりなさい、",
    "dashboard.subtitle": "今日の候補者の状況です",
    "dashboard.totalCandidates": "候補者総数",
    "dashboard.interviewsToday": "今日の面接",
    "dashboard.pendingActions": "保留中のアクション",
    "dashboard.today": "今日",
    "dashboard.followUps": "フォローアップ",
    "dashboard.notification1": "初回電話待ちの候補者が3名",
    "dashboard.notification2": "面接リマインダーが2件",
    "dashboard.notification3": "履歴書リクエストが1件",
    "dashboard.followup1": "候補者が3日間応答なし",
    "dashboard.followup2": "明日の面接リマインダー",
    "dashboard.followup3": "候補者が辞退",
    "dashboard.quickActions": "クイックアクション",
    "dashboard.viewCandidates": "すべての候補者を表示",
    "dashboard.scheduleInterview": "面接を予定",
    "dashboard.reviewResumes": "履歴書を確認",
    "dashboard.applicants": "応募者",
    
    // Notifications
    "notifications.title": "通知",
    "notifications.subtitle": "新しい通知が6件あります",
    "notifications.viewAll": "すべての通知を表示",
    
    // Calendar
    "calendar.title": "今日の面接",
    "calendar.today": "今日",
    "calendar.selectDate": "日付を選択",
    "calendar.scheduledInterviews": "予定された面接",
    "calendar.interviewsScheduled": "今日の予定された面接",
    "calendar.upcoming": "予定",
    "calendar.viewDetails": "詳細を表示",
    "calendar.reschedule": "再スケジュール",
    "calendar.sendInvite": "招待を送信",
    "calendar.shareCalendar": "カレンダーを共有",
    "calendar.close": "閉じる",
    "calendar.scheduleNew": "新しい面接を予定",
    
    // Applicants Page
    "applicants.title": "応募者",
    "applicants.subtitle": "すべての候補者応募を管理・確認",
    "applicants.searchPlaceholder": "名前または職種で検索...",
    "applicants.statusAll": "すべてのステータス",
    "applicants.statusInterviewScheduled": "面接予定",
    "applicants.statusScreening": "スクリーニング",
    "applicants.statusFirstCall": "初回電話",
    "applicants.statusOffered": "オファー済み",
    "applicants.statusRejected": "不採用",
    "applicants.statusInterview Scheduled": "面接予定",
    "applicants.statusFirst Call": "初回電話",
    "applicants.priorityHigh": "高",
    "applicants.priorityMedium": "中",
    "applicants.priorityLow": "低",
    "applicants.export": "エクスポート",
    "applicants.import": "ファイルをインポート",
    "applicants.switchToExport": "エクスポートに切り替え",
    "applicants.switchToImport": "インポートに切り替え",
    "applicants.results": "{{count}}件の結果を表示中",
    "applicants.name": "名前",
    "applicants.age": "年齢",
    "applicants.source": "ソース",
    "applicants.desiredJob": "希望職種",
    "applicants.status": "ステータス",
    "applicants.priority": "優先度",
    "applicants.nextAction": "次のアクション",
    "applicants.actions": "アクション",
    "applicants.viewProfile": "表示",
    "applicants.delete": "削除",
    "applicants.deleteConfirm": "本当に削除しますか？",
    "applicants.deleteMessage": "この操作は取り消せません。候補者は永久的に削除されます。",
    "applicants.deleteCancel": "キャンセル",
    "applicants.deleteConfirmButton": "削除",
    "applicants.newApplicants": "新規応募者",
    "applicants.newApplicantsSubtitle": "選考状態の候補者",
    "applicants.activeApplicants": "アクティブな応募者",
    "applicants.activeApplicantsSubtitle": "採用プロセス中の候補者",
    "applicants.addNew": "候補者を追加",
    "applicants.sendResumeBuilder": "履歴書作成ツールを送信",
    "applicants.sendResumeBuilderDesc": "アクティブな候補者に履歴書作成ツールのリンクを送信",
    
    // Send Resume Builder Page
    "sendResume.title": "Resume Builder",
    "sendResume.subtitle": "履歴書作成ツールのフォームを完成させるための招待を送信",
    "sendResume.backToProfile": "プロフィールに戻る",
    "sendResume.applicantDetails": "候補者詳細",
    "sendResume.name": "名前",
    "sendResume.email": "メールアドレス",
    "sendResume.message": "メッセージ",
    "sendResume.subject": "件名",
    "sendResume.messageBody": "メッセージ",
    "sendResume.linkPreview": "履歴書作成ツールのリンク（含まれます）",
    "sendResume.cancel": "キャンセル",
    "sendResume.send": "送信",
    "sendResume.sending": "送信中...",
    "sendResume.copyLink": "リンクをコピー",
    "sendResume.copied": "コピーしました！",
    "sendResume.defaultSubject": "履歴書作成ツール - 次のステップ",
    "sendResume.defaultMessage": (name: string) => `拝啓 ${name} 様,\n\nこれまでのご協力に心より感謝申し上げます。プロセスを継続するため、以下のリンクから履歴書情報を入力してください。\n\nhttps://mediverse-career.com/applicants/new/20260792/TY/applicant/resumebuilder/\n\nよろしくお願いいたします。\n\n敬具,\n大山 様`,
    "sendResume.sentSuccess": "メールが正常に送信されました！",
    "sendResume.sentSuccessMessage": "履歴書作成ツールの招待が送信されました",
    "sendResume.confirmTitle": "メール送信完了",
    "sendResume.confirmButton": "OK",
    "sendResume.close": "OK",
    
    // History
    "sendResume.history": "履歴",
    "sendResume.historyTitle": "活動履歴",
    "sendResume.noHistory": "まだ活動がありません",
    "sendResume.emailSent": "メール送信先",
    "sendResume.formStatus": "フォームの状況",
    "sendResume.notStarted": "未開始",
    "sendResume.inProgress": "進行中",
    "sendResume.completed": "完了",
    "sendResume.closeHistory": "閉じる",
    "sendResume.completionRate": "完了率",
    "sendResume.lastSent": "最終送信日",
    "sendResume.sentCount": "送信回数",
    "sendResume.resendEmail": "メールを再送信",
    "sendResume.resending": "再送信中...",
    "sendResume.resentSuccess": "メールが正常に再送信されました",
    
    // Applications Page
    "applications.title": "応募",
    "applications.subtitle": "提出された求人応募を管理",
    "applications.searchPlaceholder": "名前、職種、メールで検索...",
    "applications.results": "{{count}}件の応募を表示中",
    "applications.name": "名前",
    "applications.age": "年齢",
    "applications.desiredJob": "希望職種",
    "applications.email": "メール",
    "applications.phone": "電話",
    "applications.submittedDate": "提出日",
    "applications.actions": "アクション",
    "applications.viewProfile": "表示",
    "applications.delete": "削除",
    "applications.pendingApplications": "保留中の応募",
    "applications.pendingSubtitle": "審査待ちの応募",
    "applications.cancelledApplications": "キャンセルされた応募",
    "applications.cancelledSubtitle": "キャンセルされた応募",
    "applications.expand": "展開",
    "applications.collapse": "折りたたむ",
    "applications.deleteConfirm": "本当によろしいですか？",
    "applications.deleteMessage": "これにより、キャンセルされた応募が完全に削除されます。",
    "applications.deleteCancel": "キャンセル",
    "applications.deleteConfirmButton": "削除",
    
    // Add Candidate Page
    "addCandidate.title": "新規候補者追加",
    "addCandidate.subtitle": "データベースに候補者を追加する方法を選択してください",
    "addCandidate.backToApplicants": "応募者一覧に戻る",
    "addCandidate.manualEntry": "手動入力",
    "addCandidate.manualEntryDesc": "フォームフィールドに手動で入力",
    "addCandidate.pasteText": "テキスト貼り付け",
    "addCandidate.pasteTextDesc": "AIが候補者情報を自動解析",
    "addCandidate.uploadScreenshot": "スクリーンショットアップロード",
    "addCandidate.uploadScreenshotDesc": "AIがスクリーンショットからデータを抽出",
    "addCandidate.nameKanji": "名前（漢字）",
    "addCandidate.nameKana": "名前（かな）",
    "addCandidate.email": "メールアドレス",
    "addCandidate.phone": "電話番号",
    "addCandidate.age": "年齢",
    "addCandidate.gender": "性別",
    "addCandidate.male": "男性",
    "addCandidate.female": "女性",
    "addCandidate.other": "その他",
    "addCandidate.source": "集客元",
    "addCandidate.desiredJob": "希望職種",
    "addCandidate.addButton": "候補者を追加",
    "addCandidate.pasteTitle": "候補者情報の貼り付け",
    "addCandidate.pasteDescription": "候補者情報（履歴書テキスト、メール、プロフィールデータなど）を貼り付けると、AIが自動的に関連データを抽出して構造化します。",
    "addCandidate.pastePlaceholder": "候補者情報をこちらに貼り付けてください。例：\\\\n\\\\n名前：田中 優希 (Tanaka Yuki)\\\\n年齢：27\\\\nメール：tanaka.yuki@example.com\\\\n電話：+81 90-1234-5678\\\\n希望職種：営業マネージャー\\\\n集客元：キャリアパーク\\\\n\\\\nどんな形式でも大丈夫です - AIが解析します！",
    "addCandidate.aiPowered": "AI搭載：",
    "addCandidate.aiParseDescription": "高度なパーサーが名前、連絡先、職種の希望などをあらゆるキスト形式から抽出します。",
    "addCandidate.parseButton": "解析して候補者を追加",
    "addCandidate.processing": "処理中...",
    "addCandidate.uploadTitle": "スクリーンショットアップロード",
    "addCandidate.uploadDescription": "候補者情報のスクリーンショット（ウェブサイト、スプレッドシート、PDFその他のソースから）をアップロードすると、AIが関連データを抽出します。",
    "addCandidate.uploadText": "クリックしてアップロードまたはドラッグ＆ドロップ",
    "addCandidate.uploadFormats": "PNG、JPG、またはPDF（最大10MB）",
    "addCandidate.removeFile": "削除",
    "addCandidate.aiVision": "AIビジョン：",
    "addCandidate.aiVisionDescription": "高度なOCRとAIビジョン技術でスクリーンショットを読み取り、構造化された候補者データを自動抽出します。",
    "addCandidate.extractButton": "抽出して候補者を追加",
    "addCandidate.extracting": "データ抽出中...",
    "addCandidate.required": "*",
    
    // Applicant Profile Page
    "profile.title": "応募者プロフィール",
    "profile.backToApplicants": "応募者一覧に戻る",
    "profile.saveChanges": "変更を保存",
    "profile.section1": "セクション1 — 基本情報",
    "profile.section2": "セクション2 — 職歴",
    "profile.section3": "セクション3 — リクルーターメモ",
    "profile.timeline": "候補者タイムライン",
    "profile.nameKanji": "氏名（漢字）",
    "profile.nameKana": "氏名（カナ）",
    "profile.gender": "性別",
    "profile.male": "男性",
    "profile.female": "女性",
    "profile.other": "その他",
    "profile.dateOfBirth": "生年月日",
    "profile.age": "年齢",
    "profile.phone": "電話番号",
    "profile.email": "メールアドレス",
    "profile.leadDate": "流入日",
    "profile.university": "大学",
    "profile.currentJob": "現職",
    "profile.currentCompany": "現在の会社",
    "profile.yearsInCurrentJob": "現職の勤続年数",
    "profile.reasonForLeaving": "退職理由",
    "profile.previousJob": "前職",
    "profile.previousCompany": "前職の会社",
    "profile.yearsInPreviousJob": "前職の勤続年数",
    "profile.totalCompanies": "経験社数合計",
    "profile.totalWorkExperience": "総勤務年数",
    "profile.note1": "①転職活動の状況：",
    "profile.note2": "②現職内容／勤続年数：",
    "profile.note3": "③現職の転職理由：",
    "profile.note4": "④前職内容／勤続年数：",
    "profile.note5": "⑤前職の退職理由：",
    "profile.note6": "⑥これまでの経験社数合計：",
    "profile.note7": "⑦希望入社時期：",
    "profile.note8": "⑧希望職種：",
    "profile.note9": "⑨希望勤務地：",
    "profile.note10": "⑩現年収／希望年収：",
    "profile.summarizeWithAI": "AIで要約",
    "profile.proceedWithApplication": "応募を進める",
    "profile.cancelApplication": "応募をキャンセル",
    "profile.addNewEvent": "新しいイベントを追加",
    "profile.eventDate": "日付",
    "profile.eventDescription": "イベントの説明",
    "profile.addEvent": "追加",
    "profile.aiSummaryTitle": "AI要約",
    "profile.saveSummary": "要約を保存",
    "profile.cancelConfirm": "本当にこの応募をキャンセルしますか？",
    "profile.applicationCancelled": "応募がキャンセルされました",
    "profile.proceedingWithApplication": "応募を進めています...",
    "profile.changesSaved": "変更が正常に保存されました！",
    "profile.summarySaved": "要約が正常に保存されました！",
    "profile.match": "マッチング",
    
    // Job Match Page
    "match.title": "ジョブマッチング",
    "match.subtitle": "候補者とジョブ機会をマッチング",
    "match.backToProfile": "プロフィールに戻る",
    "match.inputMethod": "入力方法",
    "match.pasteText": "ジョブ説明を貼り付け",
    "match.uploadFile": "スクリーンショット/PDFをアップロード",
    "match.jobDescription": "ジョブ説明",
    "match.pasteJobDesc": "ここにジョブ説明テキストを貼り付け...",
    "match.uploadText": "クリックしてアップロードまたはドラッグ＆ドロップ",
    "match.uploadFormats": "PNG、JPG、またはPDF（最大10MB）",
    "match.removeFile": "削除",
    "match.analyzeCompatibility": "互換性を分析",
    "match.analyzing": "分析中...",
    "match.results": "互換性結果",
    "match.matchingScore": "マッチングスコア",
    "match.reason": "理由",
    "match.proposalReason": "提案理由",
    "match.jobImage": "ジョブ画像",
    "match.postJoinImage": "入社後の画像",
    "match.futureProspects": "将来の見通し",
    "match.addJob": "別のジョブを追加",
    "match.aiAnalyzing": "AIが候補者プロフィールとジョブ要件を分析中...",
    "match.delete": "削除",
    "match.addToProfile": "応募者プロフィールに追加",
    "match.selectJobsFirst": "プロフィールに追加するには、少なくとも1つのジョブを選択してください",
    "match.jobsAddedToProfile": "選択したジョブが応募者プロフィールに正常に追加されました！",
    
    // Resume Builder
    "resumeBuilder.title": "履歴書ビルダー",
    "resumeBuilder.subtitle": "ステップバイステップでプロフェッショナルな履歴書を作成",
    "resumeBuilder.step1": "Resume File Information",
    "resumeBuilder.step2": "ID Photo",
    "resumeBuilder.step3": "Profile",
    "resumeBuilder.step4": "Current Address",
    "resumeBuilder.step5": "Experience",
    "resumeBuilder.step6": "Motivation / Self-Promotion",
    "resumeBuilder.step7": "Commuting & Family",
    "resumeBuilder.step8": "Personal Requests",
    "resumeBuilder.step9": "Review & Submit",
    "resumeBuilder.next": "Next",
    "resumeBuilder.previous": "Previous",
    "resumeBuilder.submit": "Submit Resume",
    "resumeBuilder.fileName": "File Name",
    "resumeBuilder.fileNameNote": "採用企業が閲覧するため、適切なファイル名を使用してください。",
    "resumeBuilder.creationDate": "Creation Date",
    "resumeBuilder.idPhoto": "ID Photo",
    "resumeBuilder.uploadPhoto": "クリックしてアップロードまたはドラッグ＆ドロップ",
    "resumeBuilder.photoRequirements": "3ヶ月以内に撮影された4:3のアスペクト比の写真を提供してください。\\nサングラスや帽子は不可（NG）です。明確に識別できる写真を提供してください。\\nThe photo should be a solo shot from the chest up, with the full head visible within the frame.\\nA blue (light blue) or white background is recommended.",
    "resumeBuilder.fullName": "氏名",
    "resumeBuilder.familyName": "姓",
    "resumeBuilder.givenName": "名",
    "resumeBuilder.fullNameKana": "氏名（カナ）",
    "resumeBuilder.familyNameKana": "姓（カナ）",
    "resumeBuilder.givenNameKana": "名（カナ）",
    "resumeBuilder.dateOfBirth": "生年月日",
    "resumeBuilder.dateOfBirthNote": "年、月、日",
    "resumeBuilder.gender": "性別",
    "resumeBuilder.male": "男性",
    "resumeBuilder.female": "女性",
    "resumeBuilder.other": "その他",
    "resumeBuilder.noPhoto": "写真がアップロードされていません",
    "resumeBuilder.fullNameKanji": "氏名（漢字）",
    "resumeBuilder.postalCode": "郵便番号（必須）",
    "resumeBuilder.currentAddress": "現住所（必須）",
    "resumeBuilder.currentAddressKana": "現住所（カナ）（必須）",
    "resumeBuilder.email": "メールアドレス",
    "resumeBuilder.phoneNumber": "電話番号",
    "resumeBuilder.photoRequirementsTitle": "写真の要件：",
    "resumeBuilder.photoFormat": "PNG、JPG、JPEG（4:3のアスペクト比を推奨）",
    "resumeBuilder.reviewFileName": "ファイル名：",
    "resumeBuilder.reviewCreationDate": "作成日：",
    "resumeBuilder.reviewFamilyNameKanji": "姓（漢字）：",
    "resumeBuilder.reviewGivenNameKanji": "名（漢字）：",
    "resumeBuilder.reviewFamilyNameKana": "姓（カナ）：",
    "resumeBuilder.reviewGivenNameKana": "名（カナ）：",
    "resumeBuilder.reviewDateOfBirth": "生年月日：",
    "resumeBuilder.reviewGender": "性別：",
    "resumeBuilder.reviewPostalCode": "郵便番号：",
    "resumeBuilder.reviewCurrentAddressKanji": "現住所（漢字）：",
    "resumeBuilder.reviewCurrentAddressKana": "現住所（カナ）：",
    "resumeBuilder.reviewEmail": "メール：",
    "resumeBuilder.reviewPhoneNumber": "電話番号：",
    "resumeBuilder.reviewSkillDefault": "スキル",
    "resumeBuilder.reviewLanguageDefault": "言語",
    "resumeBuilder.workExperience": "職歴",
    "resumeBuilder.addExperience": "経歴を追加",
    "resumeBuilder.companyName": "会社名",
    "resumeBuilder.position": "役職",
    "resumeBuilder.startDate": "開始日",
    "resumeBuilder.endDate": "終了日",
    "resumeBuilder.currentlyWorking": "現在勤務中",
    "resumeBuilder.responsibilities": "主な職務と実績",
    "resumeBuilder.education": "学歴",
    "resumeBuilder.addEducation": "項目を追加",
    "resumeBuilder.schoolName": "学校名・大学名",
    "resumeBuilder.degree": "学位・資格",
    "resumeBuilder.fieldOfStudy": "専攻分野",
    "resumeBuilder.graduationDate": "卒業日",
    "resumeBuilder.skills": "専門スキル",
    "resumeBuilder.addSkill": "スキルを追加",
    "resumeBuilder.skillName": "スキル名",
    "resumeBuilder.proficiencyLevel": "習熟度",
    "resumeBuilder.beginner": "初級",
    "resumeBuilder.intermediate": "中級",
    "resumeBuilder.advanced": "上級",
    "resumeBuilder.expert": "エキスパート",
    "resumeBuilder.languages": "言語",
    "resumeBuilder.addLanguage": "言語を追加",
    "resumeBuilder.languageName": "言語",
    "resumeBuilder.languageLevel": "レベル",
    "resumeBuilder.native": "ネイティブ",
    "resumeBuilder.fluent": "流暢",
    "resumeBuilder.conversational": "会話レベル",
    "resumeBuilder.basic": "基礎",
    "resumeBuilder.reviewInfo": "情報の確認",
    "resumeBuilder.reviewDesc": "提出前にすべての情報を確認してください",
    "resumeBuilder.submitting": "提出中...",
    "resumeBuilder.successMessage": "履歴書が正常に提出されました！",
    "resumeBuilder.delete": "削除",
    "resumeBuilder.workHistory": "職歴",
    "resumeBuilder.addWork": "項目を追加",
    "resumeBuilder.licenses": "免許・資格",
    "resumeBuilder.addLicense": "項目を追加",
    "resumeBuilder.licenseName": "免許・資格名",
    "resumeBuilder.issuingOrganization": "発行機関",
    "resumeBuilder.dateObtained": "取得日",
    "resumeBuilder.highSchool": "高等学校",
    "resumeBuilder.associateDegree": "短期大学士",
    "resumeBuilder.bachelorsDegree": "学士",
    "resumeBuilder.mastersDegree": "修士",
    "resumeBuilder.doctorate": "博士",
    "resumeBuilder.yes": "はい",
    "resumeBuilder.no": "いいえ",
    "resumeBuilder.reviewSchoolDefault": "学校",
    "resumeBuilder.reviewCompanyDefault": "会社",
    "resumeBuilder.reviewLicenseDefault": "免許",
    "resumeBuilder.educationRequired": "※ 応募には少なくとも1つのエントリーが必要です",
    "resumeBuilder.motivationTitle": "志望動機・自己PR",
    "resumeBuilder.motivationPlaceholder": "例）自己PRについては別紙に記載",
    "resumeBuilder.commutingTitle": "通勤時間・家族構成",
    "resumeBuilder.commutingMethod": "通勤方法",
    "resumeBuilder.commutingTime": "通勤時間",
    "resumeBuilder.commutingTimePlaceholder": "例：1時間",
    "resumeBuilder.dependentsCount": "扶養家族数（配偶者を除く）",
    "resumeBuilder.hasSpouse": "配偶者",
    "resumeBuilder.spouseSupport": "配偶者の扶養義務",
    "resumeBuilder.personalRequestsTitle": "本人希望欄",
    "resumeBuilder.personalRequestsPlaceholder": "例）貴社の規定に従います。",
    "resumeBuilder.characterCount": "文字数：{{count}}/400",
    
    // Job Positions
    "job.productManager": "Product Manager",
    "job.dataAnalyst": "Data Analyst",
    "job.softwareEngineer": "Software Engineer",
    "job.marketingManager": "Marketing Manager",
    "job.salesRepresentative": "Sales Representative",
    "job.hrSpecialist": "HR Specialist",
    "job.uxDesigner": "UX Designer",
    
    // Statuses
    "status.newApplicant": "New Applicant",
    "status.inReview": "In Review",
    "status.interviewScheduled": "Interview Scheduled",
    "status.screening": "Screening",
    "status.firstCall": "First Call",
    "status.offered": "Offered",
    "status.rejected": "Rejected",
    
    // Sources
    "source.linkedin": "LinkedIn",
    "source.indeed": "Indeed",
    "source.referral": "Referral",
    "source.website": "Website",
    "source.careerPark": "CareerPark",
    "source.mynavi": "MyNavi",
    
    // Next Actions
    "action.scheduleInterview": "Schedule Interview",
    "action.reviewResume": "Review Resume",
    "action.firstCall": "First Call",
    "action.sendOffer": "Send Offer",
    "action.followUp": "Follow Up",
    
    // Notifications
    "notification.passwordChanged": "パスワードが正常に変更されました。",
    "notification.meetingBooked": "ミーティングの予約ありがとうございます。",
    "notification.fundLaunch": "素晴らしいニュースです！第5ファンドを開始します：DLE Senior Living。",
    "notification.author1": "ケビン・ドゥルコワン",
    "notification.author2": "マーカス・ガブリロフ",
    "notification.markAsRead": "既読にする",
    "notification.viewAll": "すべての通知を表示",
    
    // Additional Resume Builder Fields
    "resumeBuilder.applicationReason": "応募理由",
    "resumeBuilder.applicationReasonPlaceholder": "なぜこのポジションに興味を持ちましたか？",
    "resumeBuilder.selfPromotion": "自己PR・強み",
    "resumeBuilder.selfPromotionPlaceholder": "あなたの主な強みや、優れた候補者である理由を説明してください...",
    "resumeBuilder.careerGoals": "キャリア目標",
    "resumeBuilder.careerGoalsPlaceholder": "あなたのキャリアの希望は何ですか？",
    "resumeBuilder.transportationMethod": "通勤手段",
    "resumeBuilder.transportationMethodPlaceholder": "例：電車、車、自転車",
    "resumeBuilder.dependents": "扶養家族数（配偶者を除く）",
    "resumeBuilder.dependentsPlaceholder": "例：0、1、2",
    "resumeBuilder.spouseEmploymentStatus": "配偶者の就業状況",
    "resumeBuilder.selectOption": "選択してください",
    "resumeBuilder.employed": "就業中",
    "resumeBuilder.unemployed": "無職",
    "resumeBuilder.notApplicable": "該当なし",
    "resumeBuilder.salaryExpectations": "希望給与",
    "resumeBuilder.salaryExpectationsPlaceholder": "例：2,000,000円 - 5,000,000円",
    "resumeBuilder.desiredWorkLocation": "希望勤務地",
    "resumeBuilder.desiredWorkLocationPlaceholder": "例：東京、リモート",
    "resumeBuilder.startDate": "希望入社日",
    "resumeBuilder.startDatePlaceholder": "例：2026年4月",
    "resumeBuilder.otherRequests": "その他の要望",
    "resumeBuilder.otherRequestsPlaceholder": "追加の要望や考慮事項があれば記入してください...",
    "resumeBuilder.reviewMessage": "送信前にすべての情報を確認してください。",
    "resumeBuilder.confirmMessage": "送信することで、提供されたすべての情報が正確かつ完全であることを確認します。",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  // Ensure provider is mounted before rendering children
  useEffect(() => {
    setMounted(true);
  }, []);

  const t = (key: string, params?: Record<string, string | number>) => {
    let translation = translations[language][key] || key;
    
    // Replace parameters like {{count}} with actual values
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{{${param}}}`, String(params[param]));
      });
    }
    
    return translation;
  };

  // Don't return null - render children immediately with context value
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    console.error("useLanguage called outside LanguageProvider. Check that Root.tsx wraps routes with LanguageProvider.");
    throw new Error("useLanguage must be used within a LanguageProvider. Please refresh the page (Cmd/Ctrl + Shift + R)");
  }
  return context;
}

// Helper function to get translation key from value
export function getJobKey(job: string): string {
  const jobMap: Record<string, string> = {
    "Product Manager": "job.productManager",
    "Data Analyst": "job.dataAnalyst",
    "Software Engineer": "job.softwareEngineer",
    "Marketing Manager": "job.marketingManager",
    "Sales Representative": "job.salesRepresentative",
    "HR Specialist": "job.hrSpecialist",
    // Additional common job titles that might appear
    "Sales": "job.salesRepresentative",
    "Marketing": "job.marketingManager",
    "UX Designer": "job.uxDesigner",
  };
  return jobMap[job] || job;
}

export function getStatusKey(status: string): string {
  const statusMap: Record<string, string> = {
    "New Applicant": "status.newApplicant",
    "In Review": "status.inReview",
    "Interview Scheduled": "status.interviewScheduled",
    "Screening": "status.screening",
    "First Call": "status.firstCall",
    "Offered": "status.offered",
    "Rejected": "status.rejected",
  };
  return statusMap[status] || status;
}

export function getSourceKey(source: string): string {
  const sourceMap: Record<string, string> = {
    "LinkedIn": "source.linkedin",
    "Indeed": "source.indeed",
    "Referral": "source.referral",
    "Website": "source.website",
    "CareerPark": "source.careerPark",
    "Career Park": "source.careerPark",
    "MyNavi": "source.mynavi",
  };
  return sourceMap[source] || source;
}

export function getActionKey(action: string): string {
  const actionMap: Record<string, string> = {
    "Schedule Interview": "action.scheduleInterview",
    "Review Resume": "action.reviewResume",
    "First Call": "action.firstCall",
    "Send Offer": "action.sendOffer",
    "Follow Up": "action.followUp",
    // Additional actions that might appear
    "Interview tomorrow": "action.scheduleInterview",
    "Call again": "action.firstCall",
    "Technical interview": "action.scheduleInterview",
    "Awaiting response": "action.followUp",
    "Resume review": "action.reviewResume",
    "Portfolio review": "action.reviewResume",
  };
  return actionMap[action] || action;
}