import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation & Common
    'nav.home': 'Home',
    'nav.pricing': 'Pricing',
    'nav.login': 'Log In',
    'nav.signup': 'Get Started',
    'nav.dashboard': 'Dashboard',
    'nav.backToDashboard': 'Back to Dashboard',
    'nav.backToMatches': 'Back to Matches',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.continue': 'Continue',
    'common.getStarted': 'Get Started',
    'common.learnMore': 'Learn More',
    'common.contactSales': 'Contact Sales',
    'common.scheduleDemo': 'Schedule a Demo',
    'common.viewDocumentation': 'View Documentation',
    'common.scheduleCall': 'Schedule a Call',
    'common.signOut': 'Sign Out',
    'common.update': 'Update',
    'common.upgrade': 'Upgrade',
    'common.currentPlan': 'Current Plan',
    'common.mostPopular': 'Most Popular',
    'common.recommended': 'Recommended',
    'common.paid': 'Paid',
    
    // Homepage
    'home.hero.title': 'Hire for potential, not just credentials',
    'home.hero.subtitle': 'AI-powered voice insights that reveal personality, communication style, and true fit—reducing bias and transforming how you discover talent.',
    'home.hero.cta': 'Start Hiring Smarter',
    'home.hero.demo': 'See How It Works',
    'home.features.title': 'Why InishiAI?',
    'home.features.subtitle': 'Traditional hiring focuses on resumes. We focus on humans.',
    'home.feature1.title': 'Voice-Powered Insights',
    'home.feature1.desc': 'AI analyzes tone, pace, and communication patterns to reveal personality beyond the CV.',
    'home.feature2.title': 'Reduce Hiring Bias',
    'home.feature2.desc': 'Focus on traits and fit rather than credentials, leading to more diverse teams.',
    'home.feature3.title': 'Faster Decisions',
    'home.feature3.desc': 'AI-generated fit scores help you identify top candidates in minutes, not weeks.',
    'home.howItWorks.title': 'How It Works',
    'home.step1.title': 'Post Your Job',
    'home.step1.desc': 'Define the role and the traits that matter most to your team',
    'home.step2.title': 'Candidates Respond',
    'home.step2.desc': 'They answer questions via voice, revealing personality and communication style',
    'home.step3.title': 'Review AI Insights',
    'home.step3.desc': 'Get personality profiles, fit scores, and clear recommendations',
    'home.cta.title': 'Ready to transform your hiring?',
    'home.cta.subtitle': 'Join forward-thinking companies using voice insights to build better teams.',
    'home.footer.product': 'Product',
    'home.footer.features': 'Features',
    'home.footer.pricing': 'Pricing',
    'home.footer.company': 'Company',
    'home.footer.about': 'About',
    'home.footer.contact': 'Contact',
    'home.footer.legal': 'Legal',
    'home.footer.privacy': 'Privacy',
    'home.footer.terms': 'Terms',
    'home.footer.copyright': '© 2026 InishiAI. All rights reserved.',
    
    // Pricing Page
    'pricing.title': 'Simple, transparent pricing',
    'pricing.subtitle': 'Choose the plan that fits your hiring needs',
    'pricing.starter.name': 'Starter',
    'pricing.starter.desc': 'Perfect for small teams getting started',
    'pricing.starter.price': '$99',
    'pricing.starter.period': '/month',
    'pricing.starter.feature1': 'Up to 5 active job postings',
    'pricing.starter.feature2': '50 AI candidate matches per month',
    'pricing.starter.feature3': 'Basic voice insights',
    'pricing.starter.feature4': 'Email support',
    'pricing.starter.feature5': 'Standard analytics',
    'pricing.professional.name': 'Professional',
    'pricing.professional.desc': 'For growing teams hiring at scale',
    'pricing.professional.price': '$299',
    'pricing.professional.period': '/month',
    'pricing.professional.feature1': 'Up to 20 active job postings',
    'pricing.professional.feature2': '200 AI candidate matches per month',
    'pricing.professional.feature3': 'Advanced voice insights & personality analysis',
    'pricing.professional.feature4': 'Priority support',
    'pricing.professional.feature5': 'Advanced analytics & reporting',
    'pricing.professional.feature6': 'Custom interview templates',
    'pricing.professional.feature7': 'Team collaboration tools',
    'pricing.enterprise.name': 'Enterprise',
    'pricing.enterprise.desc': 'For large organizations with unique needs',
    'pricing.enterprise.price': 'Custom',
    'pricing.enterprise.feature1': 'Unlimited job postings',
    'pricing.enterprise.feature2': 'Unlimited AI candidate matches',
    'pricing.enterprise.feature3': 'Full voice & behavioral insights suite',
    'pricing.enterprise.feature4': 'Dedicated account manager',
    'pricing.enterprise.feature5': 'Custom integrations',
    'pricing.enterprise.feature6': 'API access',
    'pricing.enterprise.feature7': 'Advanced security & compliance',
    'pricing.enterprise.feature8': 'Custom training & onboarding',
    'pricing.help.title': 'Not sure which plan is right for you?',
    'pricing.help.desc': 'Schedule a demo with our team to see how InishiAI can transform your hiring process with voice-based insights.',
    
    // Login/Signup
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to your InishiAI account',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.signupLink': 'Sign up',
    'signup.title': 'Create your account',
    'signup.subtitle': 'Start hiring with AI-powered voice insights',
    'signup.name': 'Full name',
    'signup.email': 'Email address',
    'signup.password': 'Password',
    'signup.company': 'Company name',
    'signup.submit': 'Create Account',
    'signup.hasAccount': 'Already have an account?',
    'signup.loginLink': 'Sign in',
    'signup.terms': 'By signing up, you agree to our',
    'signup.termsLink': 'Terms of Service',
    'signup.and': 'and',
    'signup.privacyLink': 'Privacy Policy',
    
    // Dashboard - Sidebar
    'sidebar.jobs': 'Job Listings',
    'sidebar.candidates': 'Candidates',
    'sidebar.billing': 'Billing',
    'sidebar.settings': 'Settings',
    
    // Dashboard - Job Setup
    'jobs.title': 'Active Job Listings',
    'jobs.subtitle': 'Manage your open positions',
    'jobs.create': 'Create New Job',
    'jobs.noJobs': 'No active jobs yet',
    'jobs.noJobsDesc': 'Create your first job posting to start finding candidates',
    'jobs.status.active': 'Active',
    'jobs.status.draft': 'Draft',
    'jobs.candidates': 'candidates',
    'jobs.viewMatches': 'View Matches',
    'jobs.edit': 'Edit',
    
    // Create Job Page
    'createJob.title': 'Create New Job',
    'createJob.subtitle': 'Set up your job posting and AI matching criteria',
    'createJob.method': 'Choose how to create your job',
    'createJob.upload': 'Upload Job Description',
    'createJob.uploadDesc': 'Upload a PDF or Word document',
    'createJob.uploadBtn': 'Upload Document',
    'createJob.manual': 'Manual Entry',
    'createJob.manualDesc': 'Fill in details step by step',
    'createJob.manualBtn': 'Start From Scratch',
    'createJob.basics': 'Job Basics',
    'createJob.jobTitle': 'Job Title',
    'createJob.department': 'Department',
    'createJob.location': 'Location',
    'createJob.employmentType': 'Employment Type',
    'createJob.fullTime': 'Full-time',
    'createJob.partTime': 'Part-time',
    'createJob.contract': 'Contract',
    'createJob.description': 'Job Description',
    'createJob.descPlaceholder': 'Describe the role, responsibilities, and what success looks like...',
    'createJob.traits': 'Desired Traits & Skills',
    'createJob.traitsDesc': 'What personality traits and skills matter most?',
    'createJob.addTrait': 'Add Trait',
    'createJob.aiCriteria': 'AI Matching Criteria',
    'createJob.aiCriteriaDesc': 'Help our AI understand what makes a great fit',
    'createJob.teamCulture': 'Team Culture',
    'createJob.teamCulturePlaceholder': 'e.g., Collaborative, fast-paced, remote-first...',
    'createJob.communicationStyle': 'Preferred Communication Style',
    'createJob.commStylePlaceholder': 'e.g., Direct, detailed, visual...',
    'createJob.mustHave': 'Must-Have Qualities',
    'createJob.mustHavePlaceholder': 'e.g., Problem-solving, empathy, technical depth...',
    'createJob.saveDraft': 'Save as Draft',
    'createJob.publish': 'Publish Job',
    
    // Job Matches Page
    'matches.title': 'AI-Matched Candidates',
    'matches.for': 'for',
    'matches.sortBy': 'Sort by',
    'matches.sortMatch': 'Match Score',
    'matches.sortRecent': 'Most Recent',
    'matches.filterAll': 'All Candidates',
    'matches.filterTop': 'Top Matches (90%+)',
    'matches.filterGood': 'Good Matches (75-89%)',
    'matches.matchScore': 'Match Score',
    'matches.topQualities': 'Top qualities',
    'matches.whyGreatFit': 'Why they\'re a great fit',
    'matches.keyTraits': 'Key Traits',
    'matches.viewProfile': 'View Full Profile',
    
    // Candidate Profile Page
    'profile.scheduleInterview': 'Schedule Interview',
    'profile.aiMatchScore': 'AI Match Score',
    'profile.excellentFit': 'Excellent Fit',
    'profile.voiceAnalysis': 'Voice Analysis',
    'profile.voiceAnalysisDesc': 'AI-powered insights from voice interview',
    'profile.sampleInterview': 'Sample Interview Response',
    'profile.interviewQuestion': '"Tell us about a time you led a challenging product initiative..."',
    'profile.clearCommunicator': 'Clear Communicator',
    'profile.clearCommunicatorDesc': 'Speaks with confidence and clarity. Adjusts tone effectively based on context and audience.',
    'profile.activeListener': 'Active Listener',
    'profile.activeListenerDesc': 'Demonstrates strong listening skills with thoughtful pauses and relevant follow-up questions.',
    'profile.articulateThinker': 'Articulate Thinker',
    'profile.articulateThinkerDesc': 'Expresses complex ideas in simple terms. Uses examples and analogies to illustrate points.',
    'profile.positiveEnergy': 'Positive Energy',
    'profile.positiveEnergyDesc': 'Maintains an enthusiastic and engaging tone that motivates and inspires collaboration.',
    'profile.communicationStyle': 'Communication Style',
    'profile.communicationStyleDesc': 'How this candidate communicates and collaborates',
    'profile.collaborativeFacilitator': 'Collaborative Facilitator',
    'profile.primaryStyle': 'Primary Style',
    'profile.collaborativeDesc': 'This candidate brings teams together through active listening and clear articulation of ideas. They create inclusive environments where everyone feels heard and valued.',
    'profile.asksClarifying': 'Asks clarifying questions',
    'profile.asksClarifyingDesc': 'Ensures full understanding before moving forward',
    'profile.synthesizesFeedback': 'Synthesizes feedback well',
    'profile.synthesizesFeedbackDesc': 'Combines diverse perspectives into clear direction',
    'profile.adaptsToAudience': 'Adapts to audience',
    'profile.adaptsToAudienceDesc': 'Adjusts technical depth based on who they\'re talking to',
    'profile.providesConstructive': 'Provides constructive feedback',
    'profile.providesConstructiveDesc': 'Delivers critiques with empathy and actionable suggestions',
    'profile.commPreferences': 'Communication preferences:',
    'profile.inPersonBrainstorm': 'In-person brainstorming',
    'profile.regularCheckins': 'Regular check-ins',
    'profile.writtenDocs': 'Written documentation',
    'profile.visualPresentations': 'Visual presentations',
    'profile.keyStrengths': 'Key Strengths',
    'profile.keyStrengthsDesc': 'What this candidate excels at',
    'profile.problemSolving': 'Problem-Solving',
    'profile.problemSolvingDesc': 'Approaches challenges methodically, breaking down complex problems into actionable steps.',
    'profile.strategicThinking': 'Strategic Thinking',
    'profile.strategicThinkingDesc': 'Connects short-term decisions to long-term goals. Considers multiple stakeholder perspectives.',
    'profile.emotionalIntelligence': 'Emotional Intelligence',
    'profile.emotionalIntelligenceDesc': 'Reads team dynamics well and adapts communication style to build strong relationships.',
    'profile.recentExamples': 'Recent examples:',
    'profile.roleFit': 'Role Fit Analysis',
    'profile.overallMatch': 'Overall Match',
    'profile.technicalSkills': 'Technical Skills',
    'profile.technicalSkillsDesc': 'Strong proficiency in required tools and methodologies',
    'profile.leadershipPotential': 'Leadership Potential',
    'profile.leadershipPotentialDesc': 'Natural ability to guide and inspire team members',
    'profile.culturalAlignment': 'Cultural Alignment',
    'profile.culturalAlignmentDesc': 'Values and work style align perfectly with team culture',
    'profile.communicationFit': 'Communication Fit',
    'profile.communicationFitDesc': 'Communication style matches team dynamics',
    'profile.personalityTraits': 'Personality Traits',
    'profile.personalityInsight': 'Personality insights derived from voice patterns, word choice, and response patterns during interviews',
    'profile.whyPerfect': 'Why this candidate is perfect for this role',
    'profile.whyPerfect1': 'Leadership style matches your team\'s collaborative culture',
    'profile.whyPerfect2': 'Communication approach aligns with remote-first environment',
    'profile.whyPerfect3': 'Strategic mindset fits the senior-level responsibilities',
    'profile.whyPerfect4': 'Mentorship experience addresses team growth needs',
    
    // Billing Page
    'billing.title': 'Billing & Subscription',
    'billing.subtitle': 'Manage your plan and payment details',
    'billing.currentPlan': 'Current Plan',
    'billing.nextBilling': 'Next billing date:',
    'billing.perMonth': 'per month',
    'billing.jobPostings': 'Job Postings',
    'billing.aiMatches': 'AI Matches This Month',
    'billing.usageWarning': 'You\'re using',
    'billing.usageWarningOf': 'of your monthly AI matches',
    'billing.usageWarningUpgrade': 'Consider upgrading to the Professional plan for more matches and advanced features.',
    'billing.monthly': 'Monthly',
    'billing.annual': 'Annual',
    'billing.savePercent': 'Save 17%',
    'billing.savePerYear': 'Save',
    'billing.year': '/year',
    'billing.paymentMethod': 'Payment Method',
    'billing.expires': 'Expires',
    'billing.nextBillingCard': 'Next Billing',
    'billing.amount': 'Amount',
    'billing.date': 'Date',
    'billing.recentInvoices': 'Recent Invoices',
    'billing.download': 'Download',
    'billing.helpTitle': 'Need help choosing a plan?',
    'billing.helpDesc': 'Our team can help you find the perfect plan for your hiring needs and walk you through our AI-powered features.',
  },
  ja: {
    // Navigation & Common
    'nav.home': 'ホーム',
    'nav.pricing': '料金プラン',
    'nav.login': 'ログイン',
    'nav.signup': '始める',
    'nav.dashboard': 'ダッシュボード',
    'nav.backToDashboard': 'ダッシュボードに戻る',
    'nav.backToMatches': 'マッチ一覧に戻る',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.next': '次へ',
    'common.previous': '前へ',
    'common.continue': '続ける',
    'common.getStarted': '始める',
    'common.learnMore': '詳細を見る',
    'common.contactSales': '営業に問い合わせ',
    'common.scheduleDemo': 'デモを予約',
    'common.viewDocumentation': 'ドキュメントを見る',
    'common.scheduleCall': '通話を予約',
    'common.signOut': 'サインアウト',
    'common.update': '更新',
    'common.upgrade': 'アップグレード',
    'common.currentPlan': '現在のプラン',
    'common.mostPopular': '最も人気',
    'common.recommended': 'おすすめ',
    'common.paid': '支払済',
    
    // Homepage
    'home.hero.title': '資格だけでなく、潜在能力で採用する',
    'home.hero.subtitle': 'AIによる音声分析で、性格、コミュニケーションスタイル、真の適性を明らかにし、バイアスを減らし、人材発掘を変革します。',
    'home.hero.cta': 'スマートな採用を始める',
    'home.hero.demo': '仕組みを見る',
    'home.features.title': 'InishiAIを選ぶ理由',
    'home.features.subtitle': '従来の採用は履歴書に焦点を当てます。私たちは人に焦点を当てます。',
    'home.feature1.title': '音声による洞察',
    'home.feature1.desc': 'AIがトーン、ペース、コミュニケーションパターンを分析し、履歴書を超えた性格を明らかにします。',
    'home.feature2.title': '採用バイアスの軽減',
    'home.feature2.desc': '資格ではなく特性と適性に焦点を当て、より多様なチームを構築します。',
    'home.feature3.title': '迅速な意思決定',
    'home.feature3.desc': 'AIによる適性スコアで、週単位ではなく分単位でトップ候補者を特定できます。',
    'home.howItWorks.title': '仕組み',
    'home.step1.title': '求人を投稿',
    'home.step1.desc': '役割とチームにとって最も重要な特性を定義します',
    'home.step2.title': '候補者が応答',
    'home.step2.desc': '音声で質問に答え、性格とコミュニケーションスタイルを明らかにします',
    'home.step3.title': 'AI分析を確認',
    'home.step3.desc': '性格プロファイル、適性スコア、明確な推奨事項を取得します',
    'home.cta.title': '採用を変革する準備はできていますか？',
    'home.cta.subtitle': '音声分析を使用してより良いチームを構築する先進的な企業に参加しましょう。',
    'home.footer.product': '製品',
    'home.footer.features': '機能',
    'home.footer.pricing': '料金',
    'home.footer.company': '会社',
    'home.footer.about': '会社概要',
    'home.footer.contact': 'お問い合わせ',
    'home.footer.legal': '法務',
    'home.footer.privacy': 'プライバシー',
    'home.footer.terms': '利用規約',
    'home.footer.copyright': '© 2026 InishiAI. All rights reserved.',
    
    // Pricing Page
    'pricing.title': 'シンプルで透明な料金',
    'pricing.subtitle': 'あなたの採用ニーズに合ったプランを選択してください',
    'pricing.starter.name': 'スターター',
    'pricing.starter.desc': '始めたばかりの小規模チームに最適',
    'pricing.starter.price': '¥14,900',
    'pricing.starter.period': '/月',
    'pricing.starter.feature1': '最大5件のアクティブな求人',
    'pricing.starter.feature2': '月50件のAI候補者マッチング',
    'pricing.starter.feature3': '基本的な音声分析',
    'pricing.starter.feature4': 'メールサポート',
    'pricing.starter.feature5': '標準分析',
    'pricing.professional.name': 'プロフェッショナル',
    'pricing.professional.desc': '規模拡大中のチーム向け',
    'pricing.professional.price': '¥44,900',
    'pricing.professional.period': '/月',
    'pricing.professional.feature1': '最大20件のアクティブな求人',
    'pricing.professional.feature2': '月200件のAI候補者マッチング',
    'pricing.professional.feature3': '高度な音声分析と性格分析',
    'pricing.professional.feature4': '優先サポート',
    'pricing.professional.feature5': '高度な分析とレポート',
    'pricing.professional.feature6': 'カスタム面接テンプレート',
    'pricing.professional.feature7': 'チームコラボレーションツール',
    'pricing.enterprise.name': 'エンタープライズ',
    'pricing.enterprise.desc': '独自のニーズを持つ大規模組織向け',
    'pricing.enterprise.price': 'カスタム',
    'pricing.enterprise.feature1': '無制限の求人投稿',
    'pricing.enterprise.feature2': '無制限のAI候補者マッチング',
    'pricing.enterprise.feature3': '完全な音声・行動分析スイート',
    'pricing.enterprise.feature4': '専任アカウントマネージャー',
    'pricing.enterprise.feature5': 'カスタム統合',
    'pricing.enterprise.feature6': 'APIアクセス',
    'pricing.enterprise.feature7': '高度なセキュリティとコンプライアンス',
    'pricing.enterprise.feature8': 'カスタムトレーニングとオンボーディング',
    'pricing.help.title': 'どのプランが適しているかわかりませんか？',
    'pricing.help.desc': '私たちのチームとデモを予約して、InishiAIが音声ベースの洞察で採用プロセスをどのように変革できるかをご覧ください。',
    
    // Login/Signup
    'login.title': 'おかえりなさい',
    'login.subtitle': 'InishiAIアカウントにサインインしてください',
    'login.email': 'メールアドレス',
    'login.password': 'パスワード',
    'login.forgotPassword': 'パスワードをお忘れですか？',
    'login.submit': 'サインイン',
    'login.noAccount': 'アカウントをお持ちでないですか？',
    'login.signupLink': '新規登録',
    'signup.title': 'アカウントを作成',
    'signup.subtitle': 'AIによる音声分析で採用を開始',
    'signup.name': '氏名',
    'signup.email': 'メールアドレス',
    'signup.password': 'パスワード',
    'signup.company': '会社名',
    'signup.submit': 'アカウントを作成',
    'signup.hasAccount': 'すでにアカウントをお持ちですか？',
    'signup.loginLink': 'サインイン',
    'signup.terms': '登録することで、',
    'signup.termsLink': '利用規約',
    'signup.and': 'および',
    'signup.privacyLink': 'プライバシーポリシー',
    
    // Dashboard - Sidebar
    'sidebar.jobs': '求人一覧',
    'sidebar.candidates': '候補者',
    'sidebar.billing': '請求',
    'sidebar.settings': '設定',
    
    // Dashboard - Job Setup
    'jobs.title': 'アクティブな求人',
    'jobs.subtitle': '公開中のポジションを管理',
    'jobs.create': '新しい求人を作成',
    'jobs.noJobs': 'アクティブな求人はまだありません',
    'jobs.noJobsDesc': '最初の求人を作成して候補者を見つけましょう',
    'jobs.status.active': 'アクティブ',
    'jobs.status.draft': '下書き',
    'jobs.candidates': '候補者',
    'jobs.viewMatches': 'マッチを見る',
    'jobs.edit': '編集',
    
    // Create Job Page
    'createJob.title': '新しい求人を作成',
    'createJob.subtitle': '求人情報とAIマッチング基準を設定',
    'createJob.method': '求人の作成方法を選択',
    'createJob.upload': '求人票をアップロード',
    'createJob.uploadDesc': 'PDFまたはWordドキュメントをアップロード',
    'createJob.uploadBtn': 'ドキュメントをアップロード',
    'createJob.manual': '手動入力',
    'createJob.manualDesc': 'ステップごとに詳細を入力',
    'createJob.manualBtn': 'ゼロから始める',
    'createJob.basics': '基本情報',
    'createJob.jobTitle': '求人タイトル',
    'createJob.department': '部署',
    'createJob.location': '勤務地',
    'createJob.employmentType': '雇用形態',
    'createJob.fullTime': 'フルタイム',
    'createJob.partTime': 'パートタイム',
    'createJob.contract': '契約',
    'createJob.description': '求人内容',
    'createJob.descPlaceholder': '役割、責任、成功の姿を説明してください...',
    'createJob.traits': '求める特性とスキル',
    'createJob.traitsDesc': 'どの性格特性とスキルが最も重要ですか？',
    'createJob.addTrait': '特性を追加',
    'createJob.aiCriteria': 'AIマッチング基準',
    'createJob.aiCriteriaDesc': 'AIが最適な候補者を理解するのを助けます',
    'createJob.teamCulture': 'チーム文化',
    'createJob.teamCulturePlaceholder': '例: 協力的、スピード重視、リモートファースト...',
    'createJob.communicationStyle': '好ましいコミュニケーションスタイル',
    'createJob.commStylePlaceholder': '例: 直接的、詳細、視覚的...',
    'createJob.mustHave': '必須の資質',
    'createJob.mustHavePlaceholder': '例: 問題解決力、共感力、技術的深さ...',
    'createJob.saveDraft': '下書きとして保存',
    'createJob.publish': '求人を公開',
    
    // Job Matches Page
    'matches.title': 'AIマッチング候補者',
    'matches.for': 'の',
    'matches.sortBy': '並び替え',
    'matches.sortMatch': 'マッチスコア',
    'matches.sortRecent': '最新順',
    'matches.filterAll': 'すべての候補者',
    'matches.filterTop': 'トップマッチ（90%以上）',
    'matches.filterGood': '良いマッチ（75-89%）',
    'matches.matchScore': 'マッチスコア',
    'matches.topQualities': 'トップクオリティ',
    'matches.whyGreatFit': '最適な理由',
    'matches.keyTraits': '主な特性',
    'matches.viewProfile': '詳細プロフィールを見る',
    
    // Candidate Profile Page
    'profile.scheduleInterview': '面接を予約',
    'profile.aiMatchScore': 'AIマッチスコア',
    'profile.excellentFit': '優れた適性',
    'profile.voiceAnalysis': '音声分析',
    'profile.voiceAnalysisDesc': '音声面接からのAI分析',
    'profile.sampleInterview': 'サンプル面接の回答',
    'profile.interviewQuestion': '「困難な製品イニシアチブをリードした経験について教えてください...」',
    'profile.clearCommunicator': '明確なコミュニケーター',
    'profile.clearCommunicatorDesc': '自信を持って明確に話します。状況や聴衆に基づいてトーンを効果的に調整します。',
    'profile.activeListener': 'アクティブリスナー',
    'profile.activeListenerDesc': '思慮深い間合いと関連するフォローアップ質問で強力な傾聴スキルを示します。',
    'profile.articulateThinker': '明瞭な思考家',
    'profile.articulateThinkerDesc': '複雑なアイデアを簡単な言葉で表現します。ポイントを説明するために例や類推を使用します。',
    'profile.positiveEnergy': 'ポジティブなエネルギー',
    'profile.positiveEnergyDesc': 'コラボレーションを動機付け、刺激する熱意的で魅力的なトーンを維持します。',
    'profile.communicationStyle': 'コミュニケーションスタイル',
    'profile.communicationStyleDesc': 'この候補者のコミュニケーションと協力方法',
    'profile.collaborativeFacilitator': '協力的なファシリテーター',
    'profile.primaryStyle': '主なスタイル',
    'profile.collaborativeDesc': 'この候補者は、積極的な傾聴とアイデアの明確な表現を通じてチームをまとめます。誰もが意見を聞いてもらえる包括的な環境を作ります。',
    'profile.asksClarifying': '明確化の質問をする',
    'profile.asksClarifyingDesc': '前進する前に完全な理解を確保',
    'profile.synthesizesFeedback': 'フィードバックを統合',
    'profile.synthesizesFeedbackDesc': '多様な視点を明確な方向性に結合',
    'profile.adaptsToAudience': '聴衆に適応',
    'profile.adaptsToAudienceDesc': '話している相手に基づいて技術的深さを調整',
    'profile.providesConstructive': '建設的なフィードバックを提供',
    'profile.providesConstructiveDesc': '共感と実行可能な提案で批評を伝える',
    'profile.commPreferences': 'コミュニケーションの好み：',
    'profile.inPersonBrainstorm': '対面ブレインストーミング',
    'profile.regularCheckins': '定期的なチェックイン',
    'profile.writtenDocs': '書面ドキュメント',
    'profile.visualPresentations': 'ビジュアルプレゼンテーション',
    'profile.keyStrengths': '主な強み',
    'profile.keyStrengthsDesc': 'この候補者が優れている点',
    'profile.problemSolving': '問題解決',
    'profile.problemSolvingDesc': '複雑な問題を実行可能なステップに分解し、方法論的に課題に取り組みます。',
    'profile.strategicThinking': '戦略的思考',
    'profile.strategicThinkingDesc': '短期的な決定を長期的な目標に結びつけます。複数の利害関係者の視点を考慮します。',
    'profile.emotionalIntelligence': '感情的知性',
    'profile.emotionalIntelligenceDesc': 'チームのダイナミクスをよく読み、強い関係を築くためにコミュニケーションスタイルを適応させます。',
    'profile.recentExamples': '最近の例：',
    'profile.roleFit': '役割適性分析',
    'profile.overallMatch': '総合マッチ',
    'profile.technicalSkills': '技術スキル',
    'profile.technicalSkillsDesc': '必要なツールと方法論における強力な熟練度',
    'profile.leadershipPotential': 'リーダーシップの可能性',
    'profile.leadershipPotentialDesc': 'チームメンバーを導き、刺激する自然な能力',
    'profile.culturalAlignment': '文化的適合',
    'profile.culturalAlignmentDesc': '価値観と働き方がチーム文化と完全に一致',
    'profile.communicationFit': 'コミュニケーション適合',
    'profile.communicationFitDesc': 'コミュニケーションスタイルがチームのダイナミクスと一致',
    'profile.personalityTraits': '性格特性',
    'profile.personalityInsight': '音声パターン、語彙選択、面接中の応答パターンから導き出された性格の洞察',
    'profile.whyPerfect': 'この候補者がこの役割に最適な理由',
    'profile.whyPerfect1': 'リーダーシップスタイルがチームの協力的な文化と一致',
    'profile.whyPerfect2': 'コミュニケーションアプローチがリモートファースト環境と一致',
    'profile.whyPerfect3': '戦略的マインドセットがシニアレベルの責任に適合',
    'profile.whyPerfect4': 'メンターシップ経験がチームの成長ニーズに対応',
    
    // Billing Page
    'billing.title': '請求とサブスクリプション',
    'billing.subtitle': 'プランと支払い詳細を管理',
    'billing.currentPlan': '現在のプラン',
    'billing.nextBilling': '次回請求日：',
    'billing.perMonth': '/月',
    'billing.jobPostings': '求人投稿',
    'billing.aiMatches': '今月のAIマッチ',
    'billing.usageWarning': '月間AIマッチの',
    'billing.usageWarningOf': 'を使用中です',
    'billing.usageWarningUpgrade': 'より多くのマッチと高度な機能を得るために、プロフェッショナルプランへのアップグレードをご検討ください。',
    'billing.monthly': '月額',
    'billing.annual': '年額',
    'billing.savePercent': '17%お得',
    'billing.savePerYear': '節約',
    'billing.year': '/年',
    'billing.paymentMethod': '支払い方法',
    'billing.expires': '有効期限',
    'billing.nextBillingCard': '次回請求',
    'billing.amount': '金額',
    'billing.date': '日付',
    'billing.recentInvoices': '最近の請求書',
    'billing.download': 'ダウンロード',
    'billing.helpTitle': 'プランの選択にお困りですか？',
    'billing.helpDesc': '私たちのチームが、あなたの採用ニーズに最適なプランを見つけ、AIを活用した機能をご案内します。',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
